spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=FrameMeoirs;encrypt=false
spring.datasource.username=sa
spring.datasource.password=1qaz!QAZ
spring.thymeleaf.cache=false
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html